a = Alphabet.create!(letter: 'a')
b = Alphabet.create!(letter: 'b')
c = Alphabet.create!(letter: 'c')
d = Alphabet.create!(letter: 'd')
e = Alphabet.create!(letter: 'e')
f = Alphabet.create!(letter: 'f')
g = Alphabet.create!(letter: 'g')
h = Alphabet.create!(letter: 'h')
i = Alphabet.create!(letter: 'i')
j = Alphabet.create!(letter: 'j')
k = Alphabet.create!(letter: 'k')
l = Alphabet.create!(letter: 'l')
m = Alphabet.create!(letter: 'm')
n = Alphabet.create!(letter: 'n')
o = Alphabet.create!(letter: 'o')
pp = Alphabet.create!(letter: 'p')
q = Alphabet.create!(letter: 'q')
r = Alphabet.create!(letter: 'r')
s = Alphabet.create!(letter: 's')
t = Alphabet.create!(letter: 't')
u = Alphabet.create!(letter: 'u')
v = Alphabet.create!(letter: 'v')
w = Alphabet.create!(letter: 'w')
x = Alphabet.create!(letter: 'x')
y = Alphabet.create!(letter: 'y')
z = Alphabet.create!(letter: 'z')


Value.create!(alphabet_id: a.id, english_ordinal: 1, full_reduction: 1, reverse_ordinal: 26, reverse_full_reduction: 8)
Value.create!(alphabet_id: b.id, english_ordinal: 2, full_reduction: 2, reverse_ordinal: 25, reverse_full_reduction: 7)
Value.create!(alphabet_id: c.id, english_ordinal: 3, full_reduction: 3, reverse_ordinal: 24, reverse_full_reduction: 6)
Value.create!(alphabet_id: d.id, english_ordinal: 4, full_reduction: 4, reverse_ordinal: 23, reverse_full_reduction: 5)
Value.create!(alphabet_id: e.id, english_ordinal: 5, full_reduction: 5, reverse_ordinal: 22, reverse_full_reduction: 4)
Value.create!(alphabet_id: f.id, english_ordinal: 6, full_reduction: 6, reverse_ordinal: 21, reverse_full_reduction: 3)
Value.create!(alphabet_id: g.id, english_ordinal: 7, full_reduction: 7, reverse_ordinal: 20, reverse_full_reduction: 2)
Value.create!(alphabet_id: h.id, english_ordinal: 8, full_reduction: 8, reverse_ordinal: 19, reverse_full_reduction: 1)
Value.create!(alphabet_id: i.id, english_ordinal: 9, full_reduction: 9, reverse_ordinal: 18, reverse_full_reduction: 9)
Value.create!(alphabet_id: j.id, english_ordinal: 10, full_reduction: 1, reverse_ordinal: 17, reverse_full_reduction: 8)
Value.create!(alphabet_id: k.id, english_ordinal: 11, full_reduction: 2, reverse_ordinal: 16, reverse_full_reduction: 7)
Value.create!(alphabet_id: l.id, english_ordinal: 12, full_reduction: 3, reverse_ordinal: 15, reverse_full_reduction: 6)
Value.create!(alphabet_id: m.id, english_ordinal: 13, full_reduction: 4, reverse_ordinal: 14, reverse_full_reduction: 5)
Value.create!(alphabet_id: n.id, english_ordinal: 14, full_reduction: 5, reverse_ordinal: 13, reverse_full_reduction: 4)
Value.create!(alphabet_id: o.id, english_ordinal: 15, full_reduction: 6, reverse_ordinal: 12, reverse_full_reduction: 3)
Value.create!(alphabet_id: pp.id, english_ordinal: 16, full_reduction: 7, reverse_ordinal: 11, reverse_full_reduction: 2)
Value.create!(alphabet_id: q.id, english_ordinal: 17, full_reduction: 8, reverse_ordinal: 10, reverse_full_reduction: 1)
Value.create!(alphabet_id: r.id, english_ordinal: 18, full_reduction: 9, reverse_ordinal: 9, reverse_full_reduction: 9)
Value.create!(alphabet_id: s.id, english_ordinal: 19, full_reduction: 1, reverse_ordinal: 8, reverse_full_reduction: 8)
Value.create!(alphabet_id: t.id, english_ordinal: 20, full_reduction: 2, reverse_ordinal: 7, reverse_full_reduction: 7)
Value.create!(alphabet_id: u.id, english_ordinal: 21, full_reduction: 3, reverse_ordinal: 6, reverse_full_reduction: 6)
Value.create!(alphabet_id: v.id, english_ordinal: 22, full_reduction: 4, reverse_ordinal: 5, reverse_full_reduction: 5)
Value.create!(alphabet_id: w.id, english_ordinal: 23, full_reduction: 5, reverse_ordinal: 4, reverse_full_reduction: 4)
Value.create!(alphabet_id: x.id, english_ordinal: 24, full_reduction: 6, reverse_ordinal: 3, reverse_full_reduction: 3)
Value.create!(alphabet_id: y.id, english_ordinal: 25, full_reduction: 7, reverse_ordinal: 2, reverse_full_reduction: 2)
Value.create!(alphabet_id: z.id, english_ordinal: 26, full_reduction: 8, reverse_ordinal: 1, reverse_full_reduction: 1)